<table class="ui vertical table">
    <tbody>
        <tr>
            <th>&nbsp;</th>
            <th>First Grading</th>
            <th>Second Grading</th>
            <th>Third Grading</th>
            <th>Fourth Grading</th>
            <th>Average</th>
        </tr>
        <tr>
            <td>English</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Math</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Science</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Civics</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Christian Education</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>MTB</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>MAPEH</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Filipino</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Makadiyos</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Makatao</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Makakalikasan</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Makabansa</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>
